PROD-10: added EditCampaign page, image uploader
VitaliiChverenko/pro_dobro_react pull request #14
Opened 2018-05-15 09:51 UTC by Retttro

# Reviewers

- [ ] @okohuch
- [ ] @Antoniozinchenko
- [ ] @anastasiabalaban 

# Jira task

# Description

added EditCampaign page, image uploader

# Checklist:

- [ ] PR is approved by 1 team mate
- [ ] PR is approved by 2 experts

2018-05-15 10:14 UTC, anastasiabalaban approved these changes

2018-05-15 10:51 UTC, Antoniozinchenko requested changes

2018-05-15 10:51 UTC, Antoniozinchenko commented on src/components/campaigns/EditCampaign.js
> +      picture: props.campaign.picture,
props.campaign.picture does not exist init define image is not working

2018-05-15 10:51 UTC, Antoniozinchenko commented on src/components/campaigns/EditCampaign.js
> +      .then(() => this.close())
Run update list  callback when close popup

2018-05-15 12:54 UTC, Antoniozinchenko requested changes

2018-05-15 12:54 UTC, Antoniozinchenko commented on src/components/campaigns/CreateCampaign.js
> -        this.props.onCreated();
don't remove update callback

2018-05-16 13:50 UTC, Antoniozinchenko approved these changes

2018-05-16 13:51 UTC, merged