Add CreateCampaign Component
VitaliiChverenko/pro_dobro_react pull request #6
Opened 2018-05-09 09:05 UTC by Retttro

# Reviewers
- [ ] @okohuch
- [ ] @Antoniozinchenko 
- [ ] @anastasiabalaban

# Jira task

# Description

Add CreateCampaign Component

# Checklist:

- [ ] PR is approved by 1 team mate
- [ ] PR is approved by 2 experts

2018-05-09 10:14 UTC, anastasiabalaban commented on src/components/campaigns/CreateCampaign.js
> +              <Form.Input label="Title" type="text" value={this.state.value} onChange={this.handleTitleChange} />
You can write:
onChange={event => this.setState({title: event.target.value})}

Then you do not need a function handleTitleChange(event) and this.handleTitleChange = this.handleTitleChange.bind(this);

2018-05-09 10:14 UTC, anastasiabalaban commented on src/components/campaigns/CreateCampaign.js
> +              <Form.Input label="Needed Amount" type="text" value={this.state.value} onChange={this.handleNeededAmountChange} />
Same here

2018-05-09 10:14 UTC, anastasiabalaban commented on src/components/campaigns/CreateCampaign.js
> +            <Form.TextArea label="Description" value={this.state.value} onChange={this.handleDescriptionChange} />
Same here

2018-05-09 10:23 UTC, anastasiabalaban approved these changes

2018-05-09 15:33 UTC, Antoniozinchenko requested changes

2018-05-09 15:33 UTC, Antoniozinchenko commented on src/components/campaigns/CreateCampaign.js
> +    dbCampaigns.doCreateCampaigns(campaign.id, campaign.title,campaign.description,campaign.currentAmount,campaign.neededAmount, campaign.image)
Close modal on .then()

2018-05-09 15:33 UTC, Antoniozinchenko commented on src/components/campaigns/CreateCampaign.js
> +            <Button type="submit">Submit</Button>
add disabled prop if required inputs are empty

2018-05-09 15:33 UTC, Antoniozinchenko commented on src/components/campaigns/CreateCampaign.js
> +import React from 'react';
import React, { Component } from 'react';
use Component instead of React.Component

2018-05-10 04:57 UTC, Antoniozinchenko commented on src/components/campaigns/CreateCampaign.js
> +            neededAmount.length > 0;
const isEnabled = !(title && description && neededAmount)
or
const isEnabled = title. length && description length && neededAmount length

2018-05-10 08:30 UTC, Antoniozinchenko approved these changes

2018-05-10 08:43 UTC, merged