Develop prod 97
VitaliiChverenko/pro_dobro_react pull request #7
Opened 2018-05-09 10:42 UTC by shevchukm

# Reviewers
- [ ] @Antoniozinchenko
-[ ] @okohuch 
-[ ] @VitaliiChverenko 
# Description

add contacts page, edit modal windows, google map

# Checklist:

- [ ] PR is approved by 1 team mate
- [ ] PR is approved by 2 experts

2018-05-09 11:07 UTC, VitaliiChverenko commented on src/components/contacts/AddressAutoComplete.js
> +    </div>
Open tag has to be over the end tag

2018-05-09 11:07 UTC, VitaliiChverenko commented on src/components/contacts/AddressAutoComplete.js
> +    </div>
Use return() for multiple lines

2018-05-09 11:07 UTC, VitaliiChverenko commented on src/components/contacts/AddressAutoComplete.js
> +  })(AddressAutoComplete)
Add the line

2018-05-09 11:07 UTC, VitaliiChverenko commented on src/components/contacts/ContactForm.js
> +        this.setState({contacts: {...props.contactsData}});
too many spaces before this.setState

2018-05-09 15:41 UTC, Antoniozinchenko requested changes

2018-05-09 15:41 UTC, Antoniozinchenko commented on src/components/contacts/AddressAutoComplete.js
> +  <div class="ui label label">Address</div>
use className instead of class

2018-05-10 06:19 UTC, shevchukm commented on src/components/contacts/AddressAutoComplete.js
> +  <div class="ui label label">Address</div>
done

2018-05-10 08:28 UTC, Antoniozinchenko approved these changes

2018-05-10 08:33 UTC, merged